#!/bin/python3

import cv2
import pyautogui
import numpy as np
import threading
import os

stop = ''

def stop_recording():
  global stop
  while True:
      i = input("Enter y to stop recording? ").lower()
      stop = i
      break
    
def start_recording():
    count = 0
    screen = (1280, 1024)
    four = cv2.VideoWriter_fourcc(*"XVID")
    output = cv2.VideoWriter(f"output.avi", four, 10.0, (screen))

    fps = 120
    previous = 0
   # try:
    while True:
        if stop == 'y':
            break
        elapsed_time = time.time() - previous

        img = pyautogui.screenshot()

        if elapsed_time > 1.0 / fps:
            previous = time.time()
            frame = np.array(img)
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            output.write(frame)
        cv2.waitKey(100)
        count += 1

    cv2.destroyAllWindows()
    output.release()
    filename = input("Enter file name: ")
    try:
        os.rename('output.avi', f'{filename}.avi')
        print(f"Video saved as: {filename}.avi")
    except:
        print(f"Filename {filename} already exists")
        filename = input("Enter unique filename: ")
        os.rename('output.avi', f'{filename}.avi')
        print(f"Video saved as: {filename}.avi")


if __name__ == '__main__':
    m1 = threading.Thread(target=start_recording)
    m1.start()
    m2 = threading.Thread(target=stop_recording)
    m2.start()
